language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
  - TEST_DIR=alpha/external-api-node
  - TEST_DIR=alpha/external-web
  - TEST_DIR=alpha/internal-web
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script: cd $TEST_DIR && npm install && npm test
