language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
os: linux
env:
  - TEST_DIR=alpha/external-api-node
  - TEST_DIR=alpha/external-web
  - TEST_DIR=alpha/internal-web
script: cd $TEST_DIR && npm install && npm test
