language: node_js
node_js:
  - "6"
env:
  - TEST_DIR=alpha/external-api-node
  - TEST_DIR=alpha/external-web
  - TEST_DIR=alpha/internal-web
script: 
  - if [[ $TEST_DIR == "alpha/external-api-node" ]]
    then
      cd $TEST_DIR && npm install && npm test
    else
      cd $TEST_DIR && npm install && ./node_modules/grunt-cli/bin/grunt sync && npm test
    fi
