# Brings together the two web application and the Mongo DB and runs each of them in linked Docker containers.
version: '2'
services:

  # Build the external facing node application and expose it on port 3000.
  node-external-apvs:
    build: ./alpha/external-web
    volumes:
     - "./alpha/external-web/app:/usr/src/app/app"
     - "./alpha/external-web/public:/usr/src/app/public"
     - "./alpha/external-web/logs:/usr/src/app/logs"
     - "./alpha/uploads/eligibility-uploads:/usr/src/app/eligibility-uploads"
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  # Build the internal facing node application and expose it on port 3001.
  node-internal-apvs:
    build: ./alpha/internal-web
    volumes:
     - "./alpha/internal-web/app:/usr/src/app/app"
     - "./alpha/internal-web/public:/usr/src/app/public"
     - "./alpha/internal-web/logs:/usr/src/app/logs"
     - "./alpha/uploads/eligibility-uploads:/usr/src/app/eligibility-uploads/"
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  # Build a mongo contianer that will serve as the database for the internal and external node applications.
  mongo:
    image: mongo
    ports:
      - "27017:27017"
